import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";

const yekanBakh = localFont({
  src: [
    {
      path: "./../public/fonts/YekanBakh04Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../public/fonts/YekanBakh05Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../public/fonts/YekanBakh06Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-yekan",
  display: "swap",
});

export const metadata: Metadata = {
  title: "bilito",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${yekanBakh.variable} antialiased`}>{children}</body>
    </html>
  );
}
